/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.BitSet;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import com.google.common.collect.Lists;

public class App {

    public static void main(final String[] args) {
        final InputStream is = App.class.getClassLoader().getResourceAsStream("input.txt");
        final BufferedReader br = new BufferedReader(new InputStreamReader(is));
        final String[] lines = br.lines().toArray(String[]::new);
        long sum = 0;
        for(int i = 0; i < lines.length; i++){
            int maxVoltage = 0;
            final String[] line = lines[i].split(" ");
            final String[] correctVoltageString = line[line.length - 1].substring(1, line[0].length() - 1).split(",");
            final int[] correctVoltage = new int[correctVoltageString.length];
            for(int j = 0; j < correctVoltageString.length; j++){
                correctVoltage[j] =  Integer.parseInt(correctVoltageString[j]);
                if(maxVoltage < correctVoltage[j]){
                    maxVoltage = correctVoltage[j];
                }
            }

            final int[][] buttons = new int[line.length - 2][correctVoltage.length];
            for(int j = 1; j < line.length - 1; j++){
                final int buttonsIndex = j - 1;
                final int[] buttonLine = new int[correctVoltage.length];
                final String buttonsString = line[j].substring(1, line[j].length() - 1);
                final String[] buttonLights = buttonsString.split(",");
                for (final String buttonLight : buttonLights) {
                    buttonLine[Integer.parseInt(buttonLight)] = 1;
                }
                buttons[buttonsIndex] = buttonLine;
            }

            int hitInputSize = -1;
            for(int j = maxVoltage; hitInputSize < 1; j++){
                final List<List<Integer>> combinationList = findCombination(buttons.length, j);
                for(final List<Integer> combination : combinationList){
                    final BitSet result = new BitSet(correctVoltage.length());
                    for (final Integer buttonIndex : combination) {
                        result.xor(buttons[buttonIndex]);
                    }
                    if(result.equals(correctVoltage)){
                        hitInputSize = j;
                    }
                }
            }
            sum += hitInputSize;
            System.out.println("Hit input size for line " + i + ": " + hitInputSize);
        }
        System.out.println("Min hit input size: " + sum);
    }


    static List<List<Integer>> findCombination(final int indexesSize, final int combinationSize) {
        final int[] indexes = new int[indexesSize];
        for(int i = 0; i < indexesSize; i++){
            indexes[i] = i;
        }

        // to store the result
        final List<List<Integer>> result = new ArrayList<>();

        // Temporary array to store current combination
        final List<Integer> data = new ArrayList<>();
        combinationUtil(0, combinationSize, data, result, indexes);
        return result;
    }

    static void combinationUtil(final int index, final int combinationSize, final List<Integer> combination,
                                final List<List<Integer>> result, final int[] indexes) {
        final int indexesSize = indexes.length;

        // If size of current combination is combinationSize
        if (combination.size() == combinationSize) {
            result.add(new ArrayList<>(combination));
            return;
        }

        // Replace index with all possible elements
        for (int i = index; i < indexesSize; i++) {

            // Current element is included
            combination.add(indexes[i]);

            // Recur for next elements
            combinationUtil(i + 1, combinationSize, combination, result, indexes);

            // Backtrack to find other combinations
            combination.removeLast();
        }
    }
}
