/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import com.google.common.collect.Lists;

public class App {

    private static int[] currentLineCorrectVoltage;
    private static int[][] currentLineButtons;
    private static int lineHitInputSize;
    private static int[] currentLineResult;
    private static int currentLineCorrectVoltSum;
    private static int currentLineButtonVoltMax;
    private static int[] currentLineButtonVolts;
    private static int currentLineVoltSum;

    public static void main(final String[] args) {
        final InputStream is = App.class.getClassLoader().getResourceAsStream("testinput.txt");
        final BufferedReader br = new BufferedReader(new InputStreamReader(is));
        final String[] lines = br.lines().toArray(String[]::new);
        long sum = 0;
        for(int i = 0; i < lines.length; i++){
            lineHitInputSize = -1;
            int maxVoltage = 0;
            currentLineCorrectVoltSum = 0;
            final String[] line = lines[i].split(" ");
            final String[] correctVoltageString = line[line.length - 1].substring(1, line[line.length - 1].length() - 1).split(",");
            final int[] correctVoltage = new int[correctVoltageString.length];
            for(int j = 0; j < correctVoltageString.length; j++){
                correctVoltage[j] =  Integer.parseInt(correctVoltageString[j]);
                currentLineCorrectVoltSum += correctVoltage[j];
                if(maxVoltage < correctVoltage[j]){
                    maxVoltage = correctVoltage[j];
                }
            }
            currentLineCorrectVoltage = correctVoltage;

            final List<VoltButton> buttonList = Lists.newArrayList();
            currentLineButtonVoltMax = 0;
            for(int j = 1; j < line.length - 1; j++){
                final int[] buttonLine = new int[correctVoltage.length];
                final String buttonsString = line[j].substring(1, line[j].length() - 1);
                final String[] buttonLights = buttonsString.split(",");
                for (final String buttonLight : buttonLights) {
                    buttonLine[Integer.parseInt(buttonLight)] = 1;
                }
                int volt = buttonLights.length;
                buttonList.add(new VoltButton(volt, buttonLine));
            }
            buttonList.sort(Comparator.comparingInt(VoltButton::volt).reversed());
            currentLineButtons = buttonList.stream().map(VoltButton::volts).toArray(int[][]::new);
            currentLineButtonVolts = buttonList.stream().mapToInt(VoltButton::volt).toArray();
            currentLineButtonVoltMax = buttonList.getFirst().volt();
            System.out.println(Arrays.deepToString(currentLineButtons));
            System.out.println(Arrays.toString(currentLineButtonVolts));
            System.out.println(currentLineButtonVoltMax);

            currentLineVoltSum = 0;
            for(int j = maxVoltage; lineHitInputSize < 1; j++){
                System.out.println("Iteration with number of presses: " + j + " for line " + i);
                currentLineResult = new int[currentLineCorrectVoltage.length];
                findCombinationWithRepeat(currentLineButtons.length, j);
            }
            sum += lineHitInputSize;
            System.out.println("Hit input size for line " + i + ": " + lineHitInputSize);
        }
        System.out.println("Min hit input size: " + sum);
    }

    private record VoltButton(int volt, int[] volts) {
    }


    static List<int[]> findCombinationWithRepeat(final int indexesSize, final int combinationSize) {
        // to store the result
        final List<int[]> result = new ArrayList<>();
        // Temporary array to store current combination
        final int[] data = new int[indexesSize];
        combinationUtilForRepeating(0, combinationSize, data, result, 0);
        return result;
    }

    static void combinationUtilForRepeating(final int index, final int combinationSize, final int[] currentCombination,
                                            final List<int[]> result, int currentCombinationSum) {
        final int indexesSize = currentLineButtons.length;
        // If size of current combination is combinationSize
        final int remainingSteps = combinationSize - currentCombinationSum;
        if (remainingSteps == 0) {
            //result.add(Arrays.copyOf(currentCombination, indexesSize));
            if(Arrays.equals(currentLineCorrectVoltage, currentLineResult)){
                lineHitInputSize = combinationSize;
            }
            return;
        }
        // Replace index with all possible elements
        for (int i = index; i < indexesSize && lineHitInputSize < 1; i++) {
            // Current element is included
            //currentCombination[i]++;
            pressButtonOnResult(i, currentLineResult, 1);
            // Recur for next elements if not over target already
            if (checkIfTargetReachable(currentLineResult, currentLineCorrectVoltage, remainingSteps)){
                combinationUtilForRepeating(i, combinationSize, currentCombination, result, currentCombinationSum + 1);
            }
            // Backtrack to find other combinations
            //currentCombination[i]--;
            pressButtonOnResult(i, currentLineResult, -1);
        }
    }

    private static boolean checkIfTargetReachable(int[] currentState, int[] target, int remainingSteps){
        boolean reachable = true;
        if(currentLineCorrectVoltSum - currentLineVoltSum > remainingSteps * currentLineButtonVoltMax){
            return false;
        }
        for(int i = 0; i < target.length; i++){
            if(currentState[i] > target[i] || currentState[i] < target[i] - remainingSteps){
                reachable = false;
                //System.out.println("Unreachable target!");
                break;
            }
        }
        return reachable;
    }

    static void pressButtonOnResult(final int buttonIndex, final int[] result, final int numberOfTimes){
        currentLineVoltSum += numberOfTimes * currentLineButtonVolts[buttonIndex];
        final int[] button = currentLineButtons[buttonIndex];
        for (int l = 0; l < currentLineCorrectVoltage.length; l++) {
            result[l] += button[l] * numberOfTimes;
        }
    }

    static List<List<Integer>> findCombination(final int indexesSize, final int combinationSize) {
        final int[] indexes = new int[indexesSize];
        for(int i = 0; i < indexesSize; i++){
            indexes[i] = i;
        }
        // to store the result
        final List<List<Integer>> result = new ArrayList<>();
        // Temporary array to store current combination
        final List<Integer> data = new ArrayList<>();
        combinationUtil(0, combinationSize, data, result, indexes);
        return result;
    }

    static void combinationUtil(final int index, final int combinationSize, final List<Integer> combination,
                                final List<List<Integer>> result, final int[] indexes) {
        final int indexesSize = indexes.length;
        // If size of current combination is combinationSize
        if (combination.size() == combinationSize) {
            result.add(new ArrayList<>(combination));
            return;
        }
        // Replace index with all possible elements
        for (int i = index; i < indexesSize; i++) {
            // Current element is included
            combination.add(indexes[i]);
            // Recur for next elements
            combinationUtil(i + 1, combinationSize, combination, result, indexes);
            // Backtrack to find other combinations
            combination.removeLast();
        }
    }
}
