/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Comparator;
import java.util.List;
import com.google.common.collect.Lists;

public class App {

    private static int[] currentLineCorrectVoltage;
    private static int[][] currentLineButtons;
    private static int currentLineMachineCount;
    private static int currentLineButtonCount;
    private static int lineHitInputSize;
    private static int[] currentLineResult;
    private static int currentLineCorrectVoltSum;
    private static int currentLineButtonVoltMax;
    private static int[] currentLineButtonVolts;
    private static int currentLineVoltSum;
    private static List<int[]> currentLineStates;
    private static boolean[][] currentLineAlterable;
    private static int currentLineAlterableRelevant;

    public static void main(final String[] args) throws IOException {
        final InputStream is = App.class.getClassLoader().getResourceAsStream("input10.txt");
        final BufferedReader br = new BufferedReader(new InputStreamReader(is));
        final String[] lines = br.lines().toArray(String[]::new);
        long sum = 0;
        for(int i = 0; i < lines.length; i++){
            lineHitInputSize = -1;
            int maxVoltage = 0;
            currentLineCorrectVoltSum = 0;
            final String[] line = lines[i].split(" ");
            final String[] correctVoltageString = line[line.length - 1].substring(1, line[line.length - 1].length() - 1).split(",");
            currentLineMachineCount = correctVoltageString.length;
            final int[] correctVoltage = new int[currentLineMachineCount];
            for(int j = 0; j < currentLineMachineCount; j++){
                correctVoltage[j] =  Integer.parseInt(correctVoltageString[j]);
                currentLineCorrectVoltSum += correctVoltage[j];
                if(maxVoltage < correctVoltage[j]){
                    maxVoltage = correctVoltage[j];
                }
            }
            currentLineCorrectVoltage = correctVoltage;

            final List<VoltButton> buttonList = Lists.newArrayList();
            currentLineButtonVoltMax = 0;
            for(int j = 1; j < line.length - 1; j++){
                final int[] buttonLine = new int[currentLineMachineCount];
                final String buttonsString = line[j].substring(1, line[j].length() - 1);
                final String[] buttonLights = buttonsString.split(",");
                for (final String buttonLight : buttonLights) {
                    buttonLine[Integer.parseInt(buttonLight)] = 1;
                }
                final int volt = buttonLights.length;
                buttonList.add(new VoltButton(volt, buttonLine));
            }
            currentLineButtonCount = buttonList.size();
            buttonList.sort(Comparator.comparingInt(VoltButton::volt).reversed());
            currentLineButtons = buttonList.stream().map(VoltButton::volts).toArray(int[][]::new);
            currentLineButtonVolts = buttonList.stream().mapToInt(VoltButton::volt).toArray();
            currentLineButtonVoltMax = buttonList.getFirst().volt();
            currentLineAlterable = new boolean[currentLineButtonCount][currentLineMachineCount];
            for (int j = currentLineButtonCount - 1; j >= 0; j--) {
                for (int k = 0; k <= j; k++) {
                    for (int l = 0; l < currentLineMachineCount; l++) {
                        if(currentLineButtons[j][l] == 1){
                            currentLineAlterable[k][l] = true;
                        }
                    }
                }
            }
            for (int j = 0; j < currentLineButtonCount; j++) {
                boolean relevant = false;
                for (int k = 0; k < currentLineMachineCount; k++) {
                    if(!currentLineAlterable[j][k]){
                        relevant = true;
                        break;
                    }
                }
                if(relevant){
                    currentLineAlterableRelevant = j;
                    break;
                }
            }
            System.out.println(Arrays.deepToString(currentLineButtons));
            System.out.println(Arrays.deepToString(currentLineAlterable));
            System.out.println("Alterable relevant: " + currentLineAlterableRelevant);
            System.out.println(Arrays.toString(currentLineButtonVolts));
            System.out.println(currentLineButtonVoltMax);

            currentLineVoltSum = 0;
            for(int j = maxVoltage; lineHitInputSize < 1; j++){
                System.out.println("Iteration with number of presses: " + j + " for line " + i);
                currentLineResult = new int[currentLineCorrectVoltage.length];
                currentLineStates = new ArrayList<>(1000);
                findCombinationWithRepeat(j);
            }
            sum += lineHitInputSize;
            System.out.println("Hit input size for line " + i + ": " + lineHitInputSize);
        }
        System.out.println("Sum hit input size: " + sum);
        Path file = Path.of("aoc10result.txt");
        Files.writeString(
                file,
                String.valueOf(sum),
                StandardOpenOption.CREATE,
                StandardOpenOption.TRUNCATE_EXISTING
        );
    }

    private record VoltButton(int volt, int[] volts) {
    }


    static void findCombinationWithRepeat(final int combinationSize) {
        // Temporary array to store current combination
        combinationUtilForRepeating(0, combinationSize, 0);
    }

    static void combinationUtilForRepeating(final int index, final int combinationSize, final int currentCombinationSum) {
        final int indexesSize = currentLineButtons.length;
        // If size of current combination is combinationSize
        final int remainingSteps = combinationSize - currentCombinationSum;
        if (remainingSteps == 0) {
            if(Arrays.equals(currentLineCorrectVoltage, currentLineResult)){
                lineHitInputSize = combinationSize;
            }
            return;
        }
        // Replace index with all possible elements
        for (int i = index; i < indexesSize && lineHitInputSize < 1; i++) {
            if(i >= currentLineAlterableRelevant && !checkIfFillIsPossible(i)){
                break;
            }
            final int futureSteps = remainingSteps - 1;
            if(pressButtonOnResult(i, futureSteps)){
                combinationUtilForRepeating(i, combinationSize, currentCombinationSum + 1);
                // Backtrack to find other combinations
                removeButtonOnResult(i);
            }
        }
    }

    private static boolean checkIfFillIsPossible(final int currentIndex) {
        for(int i = 0; i < currentLineResult.length; i++){
            if(currentLineResult[i] != currentLineCorrectVoltage[i] && !currentLineAlterable[currentIndex][i]){
                return false;
            }
        }
        return true;
    }

    static boolean pressButtonOnResult(final int buttonIndex, final int remainingSteps){
        final int[] button = currentLineButtons[buttonIndex];
        final int[] tempResult = new int[currentLineResult.length];
        final int tempVoltSum = currentLineVoltSum + currentLineButtonVolts[buttonIndex];
        if (currentLineCorrectVoltSum - tempVoltSum > remainingSteps * currentLineButtonVolts[buttonIndex]){
            return false;
        }
        for (int l = 0; l < currentLineCorrectVoltage.length; l++) {
            final int result = currentLineResult[l] + button[l];
            if(result > currentLineCorrectVoltage[l] || result < currentLineCorrectVoltage[l] - remainingSteps){
                return false;
            }
            tempResult[l] = result;
        }
        currentLineStates.add(currentLineResult);
        currentLineResult = tempResult;
        currentLineVoltSum = tempVoltSum;
        return true;
    }

    static void removeButtonOnResult(final int buttonIndex){
        currentLineVoltSum -= currentLineButtonVolts[buttonIndex];
        currentLineResult = currentLineStates.getLast();
        currentLineStates.removeLast();
    }
}
